version: '3'

services:
    test:
        build:
            context: .
            dockerfile: dev.Dockerfile
        command: ./ee/bin/docker-ch-test
        volumes:
            - .:/code
        environment:
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            CLICKHOUSE_HOST: 'clickhouse'
            CLICKHOUSE_SECURE: 'false'
            CLICKHOUSE_VERIFY: 'false'
            KAFKA_URL: 'kafka://kafka'
            REDIS_URL: 'redis://redis:6379/'
            SECRET_KEY: 'alsdfjiosdajfklalsdjkf'
            DEBUG: 'true'
            TEST: 'true'
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
            - object_storage
