version: '3'

services:
  db:
    image: postgres:alpine
    container_name: posthog_db
    environment:
      POSTGRES_USER: posthog
      POSTGRES_DB: posthog
  web:
    build:
      context: .
      dockerfile: production.Dockerfile
    container_name: posthog_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      IS_DOCKER: "true"
      DATABASE_URL: "postgres://posthog@db:5432/posthog"
      SECRET_KEY: "<randomly generated secret key>"
    depends_on:
      - db
    links:
      - db:db
