[package]
name = "limiters"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
common-redis = { path = "../redis" }
dashmap = "6.1"
governor = { workspace = true }
metrics = { workspace = true }
moka = { workspace = true, features = ["sync"] }
rand = { workspace = true }
strum = { version = "0.26", features = ["derive"] }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
