[package]
name = "capture"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
axum-client-ip = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
envconfig = { workspace = true }
flate2 = { workspace = true }
health = { path = "../common/health" }
hyper = { workspace = true }
hyper-util = { workspace = true }
dashmap = { workspace = true }
common-alloc = { path = "../common/alloc" }
common-continuous-profiling = { path = "../common/continuous_profiling" }
common-redis = { path = "../common/redis" }
common-types = { path = "../common/types" }
limiters = { path = "../common/limiters" }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
rand = { workspace = true }
rdkafka = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
chrono = { workspace = true }
lz-str = { workspace = true }
multer = "3.0"
futures = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
assert-json-diff = { workspace = true }
common-continuous-profiling = { path = "../common/continuous_profiling" }
anyhow = { workspace = true }
axum-test-helper = { git = "https://github.com/posthog/axum-test-helper.git" }
futures = { workspace = true }
httparse = "1.8"
once_cell = { workspace = true }
rand = { workspace = true }
rdkafka = { workspace = true }
reqwest = { workspace = true, features = ["multipart"] }
serde_json = { workspace = true }
