[package]
name = "ingestion-consumer"
version = "0.0.1"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
envconfig = { workspace = true }
futures = { workspace = true }
metrics = { workspace = true }
rdkafka = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
siphasher = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

common-alloc = { path = "../common/alloc" }
common-kafka = { path = "../common/kafka" }
common-metrics = { path = "../common/metrics" }

[dev-dependencies]
httpmock = { workspace = true }
