[package]
name = "ingestion-consumer"
version = "0.0.1"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
crossterm = { workspace = true }
envconfig = { workspace = true }
futures = { workspace = true }
metrics = { workspace = true }
prost = { workspace = true }
ratatui = { workspace = true }
rdkafka = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
siphasher = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

common-alloc = { path = "../common/alloc" }
common-kafka = { path = "../common/kafka" }
common-metrics = { path = "../common/metrics" }
common-types = { path = "../common/types" }
health = { path = "../common/health" }

[build-dependencies]
tonic-build = "0.12"

[package.metadata.cargo-shear]
ignored = ["prost"]
