[package]
name = "links"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1.88"
axum = { workspace = true }
common-alloc = { path = "../common/alloc" }
common-database = { path = "../common/database" }
common-kafka = { path = "../common/kafka" }
common-metrics = { path = "../common/metrics" }
common-redis = { path = "../common/redis" }
common-types = { path = "../common/types" }
chrono = { workspace = true }
envconfig = { workspace = true }
health = { path = "../common/health" }
once_cell = "1.18.0"
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["rust_decimal"] }
rand = { workspace = true }
rdkafka = { workspace = true }
rust_decimal = "1.37.1"
thiserror = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true, features = ["v4"] }

[lints]
workspace = true

[dev-dependencies]
reqwest = { workspace = true }
