[package]
name = "posthog-cli"
version = "0.0.1"
authors = [
    "David <david@posthog.com>",
    "Olly <oliver@posthog.com>",
    "Hugues <hugues@posthog.com>",
]
description = "The command line interface for PostHog ðŸ¦”"
homepage = "https://posthog.com"
license = "MIT"
edition = "2021"

[[bin]]
name = "posthog-cli"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.31", features = ["derive"] }
dirs = "6.0.0"
inquire = "0.7.5"
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
common-symbol-data = { path = "../common/symbol_data" }

[lints]
workspace = true
