[package]
name = "common-redis"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
redis = { workspace = true }
serde-pickle = { version = "1.1.1" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zstd = "0.13"

