[package]
name = "log-capture"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
envconfig = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
health = { path = "../common/health" }
axum = { workspace = true }
common-metrics = { path = "../common/metrics" }
common-alloc = { path = "../common/alloc" }
capture = { path = "../capture" }
opentelemetry-proto = { workspace = true }
tonic = { workspace = true }
tonic-web = { workspace = true }
tower = { workspace = true }
jsonwebtoken = "8.3"
serde = { workspace = true }
serde_derive = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
clickhouse = { workspace = true }
serde_json = { workspace = true }
metrics = { workspace = true }
base64 = { workspace = true }
rdkafka = { workspace = true }
sha2 = "0.10.8"
uuid = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
