[package]
name = "capture-logs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
envconfig = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
health = { path = "../common/health" }
axum = { workspace = true }
common-metrics = { path = "../common/metrics" }
common-alloc = { path = "../common/alloc" }
common-continuous-profiling = { path = "../common/continuous_profiling" }
limiters = { path = "../common/limiters" }
capture = { path = "../capture" }
opentelemetry-proto = { workspace = true }
tonic = { workspace = true }
jsonwebtoken = "8.3"
serde = { workspace = true }
serde_derive = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
clickhouse = { workspace = true }
serde_json = { workspace = true }
metrics = { workspace = true }
base64 = { workspace = true }
rdkafka = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
apache-avro = { version = "0.21.0", features = ["zstandard"] }
prost = "0.13.5"
bytes = { workspace = true }
tower-http = { workspace = true }

[lints]
workspace = true
