# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 139
  version: 1
  created_at: '2026-01-14T10:18:06.407250+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:06.407360+00:00'
  last_modified_by: ~
  checksum: sha256:b6320aa96522223d
  last_synced: '2026-01-15T10:28:55.118442+00:00'
key: test-copy-remote-config
name: test-copy-remote-config
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
