# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 170
  version: 1
  created_at: '2026-01-14T10:18:07.435203+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:07.435281+00:00'
  last_modified_by: ~
  checksum: sha256:ecbcd3433bb9c3d1
  last_synced: '2026-01-15T10:28:55.071527+00:00'
key: edit_dwh_source_config
name: edit_dwh_source_config
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
