# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 250
  version: 1
  created_at: '2026-01-14T10:18:10.050827+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:10.050908+00:00'
  last_modified_by: ~
  checksum: sha256:139a9101bab92019
  last_synced: '2026-01-15T10:28:54.893017+00:00'
key: replay-settings-help
name: replay-settings-help
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
