# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 383
  version: 1
  created_at: '2026-01-14T10:18:15.657405+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:15.657483+00:00'
  last_modified_by: ~
  checksum: sha256:f2d244cd2169e9aa
  last_synced: '2026-01-15T10:28:54.509394+00:00'
key: error-tracking-embedding-configuration
name: error-tracking-embedding-configuration
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
