# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 505
  version: 1
  created_at: '2026-01-14T10:18:37.360276+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:37.360367+00:00'
  last_modified_by: ~
  checksum: sha256:59aa9e74ad65bee4
  last_synced: '2026-01-15T10:28:54.043057+00:00'
key: settings-persons-on-events-hidden
name: settings-persons-on-events-hidden
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
