# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 526
  version: 1
  created_at: '2026-01-14T10:18:38.294189+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:38.294269+00:00'
  last_modified_by: ~
  checksum: sha256:59e306a4006a4996
  last_synced: '2026-01-15T10:28:54.014964+00:00'
key: environments
name: environments
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
