# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 535
  version: 1
  created_at: '2026-01-14T10:18:38.982830+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:38.982904+00:00'
  last_modified_by: ~
  checksum: sha256:4de71b84533e422c
  last_synced: '2026-01-15T10:28:54.003142+00:00'
key: settings-bounce-rate-page-view-mode
name: settings-bounce-rate-page-view-mode
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
