# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 537
  version: 1
  created_at: '2026-01-14T10:18:39.079225+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:39.079338+00:00'
  last_modified_by: ~
  checksum: sha256:2a85198261eccd3f
  last_synced: '2026-01-15T10:28:53.999990+00:00'
key: settings-session-table-version
name: settings-session-table-version
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
