# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 538
  version: 1
  created_at: '2026-01-14T10:18:39.127809+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:39.127898+00:00'
  last_modified_by: ~
  checksum: sha256:741e26094a551369
  last_synced: '2026-01-15T10:28:53.998986+00:00'
key: settings-sessions-v2-join
name: settings-sessions-v2-join
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
