# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 560
  version: 1
  created_at: '2026-01-14T10:18:40.129889+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:40.129962+00:00'
  last_modified_by: ~
  checksum: sha256:17a0c1b50b524bc5
  last_synced: '2026-01-15T10:28:53.969347+00:00'
key: default-evaluation-environments
name: default-evaluation-environments
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
