# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 607
  version: 1
  created_at: '2026-01-14T10:18:42.436248+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:42.436340+00:00'
  last_modified_by: ~
  checksum: sha256:c55fb9035add51f8
  last_synced: '2026-01-15T10:28:53.894113+00:00'
key: remote-config
name: remote-config
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
