# PostHog Feature Flag - team-1
_meta:
  type: feature_flag
  id: 86
  version: 1
  created_at: '2026-01-14T10:18:04.036145+00:00'
  created_by:
    id: 1
    email: test@posthog.com
    first_name: Employee 427
  updated_at: '2026-01-14T10:18:04.036312+00:00'
  last_modified_by: ~
  checksum: sha256:508b1405b3491e8e
  last_synced: '2026-01-15T10:28:55.200043+00:00'
key: advance-marketing-analytics-settings
name: advance-marketing-analytics-settings
active: true
ensure_experience_continuity: false
filters:
  groups:
  - properties: []
    rollout_percentage: 100
  payloads: {}
rollout_percentage: 100
