[package]
name = "cyclotron-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.88.0" # please keep in sync with the version in .github/workflows/rust.yml
publish = false

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
common-compression = { path = "../common/compression" }
common-metrics = { path = "../common/metrics" }
csv = "1.3.1"
hex = "0.4.3"
