[package]
name = "common-types"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rdkafka = { workspace = true }
rust_decimal = "1.37.1"
sqlx = { workspace = true, features = ["rust_decimal"] }
uuid = { workspace = true }
time = { workspace = true }
dateparser = "0.2"
jiff = "0.1"
regex = { workspace = true }
