[package]
name = "cyclotron-node"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]
publish = false

[lints]
workspace = true


[lib]
crate-type = ["cdylib"]

[dependencies]
cyclotron-core = { path = "../cyclotron-core" }
neon = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
