#
# Build and push PostHog container images for AI evaluations to AWS ECR
#
# - posthog_ai_evals_build: build and push the PostHog container image to AWS ECR
#
name: AI Evals Container Images CD

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'rust/**'
            - 'livestream/**'
            - 'nodejs/**'
    pull_request:
    workflow_dispatch:

jobs:
    posthog_ai_evals_build:
        name: Build and push container image
        if: |
            github.repository == 'PostHog/posthog' && (
                github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'build-ai-evals-image')
            )
        runs-on: depot-ubuntu-latest
        permissions:
            id-token: write # allow issuing OIDC tokens for this workflow run
            contents: read # allow at least reading the repo contents, add other permissions if necessary

        steps:
            - name: Check out
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
              with:
                  fetch-depth: 2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

            - name: Set up QEMU
              uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

            - name: Set up Depot CLI
              uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5 # v1.6.0

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
              with:
                  role-to-assume: ${{ secrets.AWS_ECR_PUBLISH_IAM_ROLE }}
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: aws-ecr
              uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

            - name: Build and push container image
              id: build
              uses: depot/build-push-action@9785b135c3c76c33db102e45be96a25ab55cd507 # v1.16.2
              with:
                  project: c1f2m5s6zd
                  file: ./Dockerfile.ai-evals
                  buildx-fallback: false # the fallback is so slow it's better to just fail
                  push: true
                  tags: ${{ github.ref == 'refs/heads/master' && format('{0}/posthog-ai-evals:master,{0}/posthog-ai-evals:{1}', steps.aws-ecr.outputs.registry, github.sha) || format('{0}/posthog-ai-evals:{1}', steps.aws-ecr.outputs.registry, github.sha) }}
                  platforms: linux/arm64,linux/amd64
                  build-args: COMMIT_HASH=${{ github.sha }}
