on:
    push:
        branches:
            - master
    pull_request:
    merge_group:

name: Security

permissions:
    contents: read

env:
    SEMGREP_ENABLE_VERSION_CHECK: 'false'

jobs:
    ensure-pinned-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Ensure SHA pinned actions
              uses: zgosalvez/github-actions-ensure-sha-pinned-actions@9e9574ef04ea69da568d6249bd69539ccc704e74 # v4.0.0
              with:
                  allowlist: |
                      actions/
                      aws-actions/
                      docker/
                      github/
                      hashicorp/
                      PostHog/
                      tailscale/

    semgrep-python:
        runs-on: ubuntu-latest
        container:
            image: returntocorp/semgrep

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Semgrep
              run: |
                  semgrep \
                    --config "p/python" \
                    --config "p/owasp-top-ten" \
                    --config "p/trailofbits" \
                    --error \
                    --metrics=off \
                    --verbose \
                    --exclude-rule trailofbits.generic.redis-unencrypted-transport.redis-unencrypted-transport \
                    dags/ ee/ posthog/ products/

    semgrep-go:
        runs-on: ubuntu-latest
        container:
            image: returntocorp/semgrep

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Semgrep
              run: |
                  semgrep \
                    --config "p/golang" \
                    --config "p/owasp-top-ten" \
                    --config "p/security-audit" \
                    --config "p/trailofbits" \
                    --error \
                    --metrics=off \
                    --verbose \
                    livestream/

    semgrep-rust:
        runs-on: ubuntu-latest
        container:
            image: returntocorp/semgrep

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Semgrep
              run: |
                  semgrep \
                    --config "p/rust" \
                    --config "p/owasp-top-ten" \
                    --config "p/security-audit" \
                    --config "p/trailofbits" \
                    --error \
                    --metrics=off \
                    --verbose \
                    --exclude-rule trailofbits.generic.curl-unencrypted-url.curl-unencrypted-url \
                    --exclude-rule trailofbits.generic.redis-unencrypted-transport.redis-unencrypted-transport \
                    --exclude-rule trailofbits.rs.panic-in-function-returning-result.panic-in-function-returning-result \
                    rust/

    semgrep-js:
        runs-on: ubuntu-latest
        container:
            image: returntocorp/semgrep

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Semgrep
              run: |
                  semgrep \
                    --config "p/javascript" \
                    --config "p/owasp-top-ten" \
                    --config "p/security-audit" \
                    --config "p/trailofbits" \
                    --error \
                    --metrics=off \
                    --verbose \
                    plugin-server/
