# Generates the `posthog/posthog:latest-release` & `posthog/posthog:release-[version]` Docker images
# and pushes to Docker Hub
name: Docker release image

on:
    push:
        tags:
            - '*.**'

jobs:
    build-push:
        name: Build & push Docker release image
        if: github.repository == 'PostHog/posthog'
        runs-on: ubuntu-20.04
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout default branch
              uses: actions/checkout@v3

            - name: Get tag name
              run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | tr / -)" >> $GITHUB_ENV

            - name: Update git SHA
              run: echo "GIT_SHA = '${GITHUB_SHA}'" > posthog/gitsha.py

            - name: Set up Depot CLI
              uses: depot/setup-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push release
              id: docker-release
              uses: depot/build-push-action@v1
              with:
                  context: .
                  push: true
                  tags: |
                      posthog/posthog:latest-release
                      posthog/posthog:release-${{ env.TAG_NAME  }}
                  buildx-fallback: true # if Depot builder is unavailable, fall back to local buildx
                  platforms: linux/amd64,linux/arm64

            - name: Image digest
              run: |
                  echo "Pushed release: ${{ steps.docker-release.outputs.digest }}"
