name: Build DockerHub image

on:
    push:
        branches:
            - master
            - main

concurrency: 'publish_latest_image' # Ensure only one of this runs at a time

jobs:
    build-push:
        name: Build Docker images and push them
        if: github.repository == 'PostHog/posthog'
        runs-on: ubuntu-20.04
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout default branch
              uses: actions/checkout@v2

            - name: Update git sha
              run: echo "GIT_SHA = '${GITHUB_SHA}'" >posthog/gitsha.py

            - name: Set up Depot CLI
              uses: depot/setup-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push latest
              id: docker-latest
              uses: depot/build-push-action@v1
              with:
                  context: .
                  push: true
                  tags: posthog/posthog:latest
              timeout-minutes: 60

            - name: Image digests
              run: |
                  echo "Pushed latest: ${{ steps.docker-latest.outputs.digest }}"
                  echo "Pushed dev: ${{ steps.docker-dev.outputs.digest }}"
