name: Docker
on:
    - pull_request

jobs:
    build:
        name: Vulnerabilty Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              if: github.repository == 'PostHog/posthog'
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build image
              uses: docker/build-push-action@v2
              if: github.repository == 'PostHog/posthog'
              with:
                  push: true
                  tags: posthog/posthog:vuln-scan-${{ github.sha }}

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              if: github.repository == 'PostHog/posthog'
              with:
                  image-ref: 'posthog/posthog:vuln-scan-${{ github.sha }}'
                  format: 'template'
                  template: '@/contrib/sarif.tpl'
                  output: 'trivy-results.sarif'

            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v1
              if: github.repository == 'PostHog/posthog'
              with:
                  sarif_file: 'trivy-results.sarif'
