# Generates the `posthog/posthog:release-[version]-unstable` Docker image and pushes to Docker Hub
# when a branch that matches `release-[version]` is pushed. Image can be used for break the release sessions.
name: Docker unstable image for code freeze

on:
    push:
        branches:
            - 'release-*.*'

jobs:
    build-release-push:
        name: Build & push Docker release image
        if: github.repository == 'PostHog/posthog'
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout default branch
              uses: actions/checkout@v2

            - name: Get branch name
              run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

            - name: Update git SHA
              run: echo "GIT_SHA = '${GITHUB_SHA}'" > posthog/gitsha.py

            - name: Set up Depot CLI
              uses: depot/setup-depot@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push release
              id: docker-release
              uses: depot/build-push-action@v1
              with:
                  context: .
                  push: true
                  tags: posthog/posthog:${{ env.BRANCH_NAME  }}-unstable
                  token: ${{ secrets.DEPOT_TOKEN }}

            - name: Image digest
              run: |
                  echo "Pushed release: ${{ steps.docker-release.outputs.digest }}"
