name: Updated PR

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize
    # allow this to be triggered after committing with the GITHUB_TOKEN
    repository_dispatch:
        types: [pr-update]

jobs:
    lint-pr:
        name: Validate PR title against Conventional Commits
        runs-on: ubuntu-24.04
        steps:
            - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
