name: 'Handle stale PRs'
on:
    schedule:
        - cron: '30 7 * * 1-5'

jobs:
    stale:
        # Only unleash the stale bot on PostHog/posthog, as there's no POSTHOG_BOT_PAT token on forks
        if: ${{ github.repository == 'PostHog/posthog' }}
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/stale@v9
              with:
                  days-before-issue-stale: 730
                  days-before-issue-close: 14
                  stale-issue-message: "This issue hasn't seen activity in two years! If you want to keep it open, post a comment or remove the `stale` label – otherwise this will be closed in two weeks."
                  close-issue-message: "This issue was closed due to lack of activity. Feel free to reopen if it's still relevant."
                  stale-issue-label: stale
                  remove-issue-stale-when-updated: true
                  days-before-pr-stale: 7
                  days-before-pr-close: 7
                  stale-pr-message: "This PR hasn't seen activity in a week! Should it be merged, closed, or further worked on? If you want to keep it open, post a comment or remove the `stale` label – otherwise this will be closed in another week. If you want to permanentely keep it open, use the `waiting` label."
                  close-pr-message: "This PR was closed due to lack of activity. Feel free to reopen if it's still relevant."
                  stale-pr-label: stale
                  remove-pr-stale-when-updated: true
                  exempt-pr-labels: 'waiting'
                  operations-per-run: 250
                  repo-token: ${{ secrets.POSTHOG_BOT_PAT }}
