name: 'Storybook Deployment'
on:
    push:
        branches:
            - master
            - main

jobs:
    storybook-deployment:
        runs-on: ubuntu-24.04
        if: github.repository == 'PostHog/posthog'
        steps:
            - name: Check out PostHog/posthog repo
              uses: actions/checkout@v4
              with:
                  path: posthog

            - name: Install pnpm
              uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
              with:
                  package_json_file: posthog/package.json

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.17.1
                  cache: pnpm
                  cache-dependency-path: posthog/pnpm-lock.yaml

            - name: Install dependencies (pnpm)
              run: cd posthog && pnpm --filter=@posthog/storybook... install --frozen-lockfile

            - name: Build storybook
              run: cd posthog && bin/turbo --filter=@posthog/storybook build

            - name: Check out PostHog/storybook-build repo
              uses: actions/checkout@v4
              with:
                  path: storybook-build
                  repository: PostHog/storybook-build
                  token: ${{ secrets.POSTHOG_BOT_PAT }}

            - name: Copy built changes to PostHog/storybook-build repo
              run: |
                  # keep the CNAME file, but discard all the rest
                  cp storybook-build/docs/CNAME posthog/common/storybook/dist/
                  rm -rf storybook-build/docs
                  cp -a posthog/common/storybook/dist storybook-build/docs

            - name: Set commit message
              id: commit-message
              run: echo "msg=Storybook build for ${{ github.sha }}" >> $GITHUB_OUTPUT

            - name: Commit update
              uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
              with:
                  repository: storybook-build
                  commit_message: ${{ steps.commit-message.outputs.msg }}
                  commit_user_name: PostHog Bot
                  commit_user_email: hey@posthog.com
                  commit_author: PostHog Bot <hey@posthog.com>
