name: Version Update

on:
    push:
        tags:
            - '*.**'

jobs:
    update-version:
        name: Update VERSION
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  ref: master
                  fetch-depth: 0

            - name: Edit version.py
              run: echo "VERSION = \"$(git describe --tags `git rev-list --tags --max-count=1`)\"" > posthog/version.py

            - name: Commit update
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'Update VERSION'
                  commit_user_name: PostHog Bot
                  commit_user_email: hey@posthog.com
                  commit_author: PostHog Bot <hey@posthog.com>
